"""Tiny offline tokenizer: word-level, built from the training corpus.

No downloads, no network: the vocab is generated by src/make_data.py's
sibling step (see build()) and committed at data/vocab.json. The
--model-source pretrained path uses the HuggingFace tokenizer instead.
"""

from __future__ import annotations

import json
import re
from collections import Counter

PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"
EOS_TOKEN = "<eos>"

_TOKEN_RE = re.compile(r"[a-z0-9]+|[^a-z0-9\s]")


def tokenize_text(text: str) -> list[str]:
    return _TOKEN_RE.findall(text.lower())


class SimpleTokenizer:
    def __init__(self, vocab: dict[str, int]):
        self.vocab = dict(vocab)
        self.inv_vocab = {i: t for t, i in vocab.items()}
        self.pad_token_id = vocab[PAD_TOKEN]
        self.unk_token_id = vocab[UNK_TOKEN]
        self.eos_token_id = vocab[EOS_TOKEN]

    @classmethod
    def build(cls, texts: list[str]) -> "SimpleTokenizer":
        counts = Counter()
        for text in texts:
            counts.update(tokenize_text(text))
        vocab = {PAD_TOKEN: 0, UNK_TOKEN: 1, EOS_TOKEN: 2}
        for token in sorted(counts):
            vocab[token] = len(vocab)
        return cls(vocab)

    def encode(self, text: str, add_eos: bool = False) -> list[int]:
        ids = [self.vocab.get(t, self.unk_token_id) for t in tokenize_text(text)]
        if add_eos:
            ids.append(self.eos_token_id)
        return ids

    def decode(self, ids: list[int]) -> str:
        tokens = [self.inv_vocab.get(i, UNK_TOKEN) for i in ids]
        # Rejoin: no space before punctuation.
        out = ""
        for tok in tokens:
            if tok in (PAD_TOKEN, EOS_TOKEN):
                continue
            if re.fullmatch(r"[^a-z0-9]", tok) and out:
                out += tok
            else:
                out += (" " if out else "") + tok
        return out

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.vocab, f, indent=1)

    @classmethod
    def load(cls, path: str) -> "SimpleTokenizer":
        with open(path, encoding="utf-8") as f:
            vocab = json.load(f)
        return cls({k: int(v) for k, v in vocab.items()})

    def __len__(self) -> int:
        return len(self.vocab)
